apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prerender
  name: prerender
  namespace: prerender-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prerender
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prerender
    spec:
      containers:
      - image: koton00beng/prerender:v2.0
        name: prerender
        ports:
        - containerPort: 8080
        - containerPort: 3000
        env:
        - name: ADMIN_USERNAME
          value: "admin123"
        - name: ADMIN_PASSWORD
          value: "jcotoadmin"
        - name: BASIC_AUTH_USERNAME
          value: "admin123"
        - name: BASIC_AUTH_PASSWORD
          value: "jcotoadmin"
        - name: REDIS_URL
          value: "tredis-master.redis.svc.cluster.local"
        - name: JWT_TOKEN
          value: "XnIfVmS9qUVrk@8QDXESz8GyfOdLxCR7^58EI3#Ld$DX"
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prerender
  name: prerender
  namespace: prerender-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: prerender
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: prerenderendpoints
  selector:
    app: prerender
status:
  loadBalancer: {}

